Made changes to support elasticsearch 5
Matityahul/tornado-es-ext pull request #1
Opened 2017-08-17 11:39 UTC by Matityahul

2017-08-17 18:09 UTC, sxtomerg requested changes

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +    _MATCH_ALL_QUERY = {"query": {"match_all": {}}}
First time someone name this query. nice.. :)

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +    # TODO : timeout, max_retries, retry_on_timeout
TODO?

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +        path = "/%(index)s/%(type)s/_%(method)s" % {"method": method, "index": index, "type": type}
You have the words (method, index, type) defined 3 times in the same line (TERSE 👎 ) :)

what about "/{}/{}/{}".format(method, index, type)

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +    def _create_query_string(params):
This method should be beneath "from_uri" and "request_document"

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +    def create_path(method, index='_all', type='', **kwargs):
"method_name" better describes the parameter

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
>          url = '%(url)s%(path)s?%(querystring)s' % {
url, path, querystring is written 3 times :)
I know it's not your code :P

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/tests/unit/test_tornadoes.py
> +        if self.version < 5:
I don't know where you are getting the version parameter, 
but it seems that you should know in the test which version it is and assert according to it.
Maybe separate to 2 unit tests with two different versions

2017-08-17 18:09 UTC, sxtomerg commented on tornadoes/__init__.py
> +        self.http_request_kwargs = http_request_kwargs or {}
good renaming :)

2017-08-19 18:04 UTC, Matityahul commented on tornadoes/__init__.py
> +        path = "/%(index)s/%(type)s/_%(method)s" % {"method": method, "index": index, "type": type}
you understand that's not my code right?
There are a lot more things I would change in this code but I changed almost only what I must changed.
But anyway, I don't think it's so bad the way they wrote it, I would prefer it by your way.

2017-08-19 18:06 UTC, Matityahul commented on tornadoes/__init__.py
> +    def create_path(method, index='_all', type='', **kwargs):
I can't change parameter names, I want to suggest my changes as a pull-request to the original repository too, I can't change the API...

2017-08-19 18:11 UTC, Matityahul commented on tornadoes/__init__.py
> +    def _create_query_string(params):
I always write private methods before public methods. I know what you think about the order of method but I don't agree with you.

2017-08-20 09:38 UTC, sxtomerg approved these changes

2017-08-20 10:57 UTC, tomer-senexx commented on tornadoes/__init__.py
> +    _MATCH_ALL_QUERY = {"query": {"match_all": {}}}
Very nice, but just note that usually class variables should be in lower case

2017-08-20 10:57 UTC, tomer-senexx commented on tornadoes/__init__.py
> +        Support Elasticsearch 5.X
Please add one more comment about what you are trying to do here, why is it necessary to ES 5..

2017-08-20 14:34 UTC, merged